/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Live Stellar Testnet journey — the complete user flow, reproducibly.
 *
 * Boots against a running local gateway (see scripts/testnet-journey.sh) and
 * a live Stellar Testnet:
 *
 *   1. Funds three fresh accounts (friendbot): ISSUER, PAYER, RECEIVER
 *   2. PAYER adds a trustline for `USDC:ISSUER`; ISSUER mints 100 USDC
 *   3. Unpaid request → HTTP 402 with a quote (captured verbatim)
 *   4. PAYER submits the quoted payment (repo `@x402/wallet` builder)
 *   5. Retry with X-Payment-Hash → HTTP 200 + X-Payment-Receipt header
 *   6. Replay the SAME hash → HTTP 402 "already been used" (single-use)
 *   7. A never-existing hash → HTTP 402 "Transaction not found" (fail-closed)
 *
 * Evidence (full tx hashes, ledger, balances, Horizon links) is written to
 * a JSON file and printed as a table, so every claim is independently
 * verifiable. Deterministic failure: any unexpected status fails the run.
 *
 * Run via `scripts/testnet-journey.sh` (or bundle with esbuild and set the
 * env vars below).
 */
import {
  Keypair,
  Operation,
  Asset,
  TransactionBuilder,
  Networks,
  BASE_FEE,
  Memo,
  MemoText,
  Horizon,
} from '@stellar/stellar-sdk';
import { buildPaymentTransaction } from '@x402/wallet';
import { stroopsToUnits } from '@x402/shared';
import { prisma } from '@x402/database';

// ── Config ────────────────────────────────────

const GATEWAY_URL = process.env.GATEWAY_URL || 'http://127.0.0.1:3000';
const HORIZON_URL = process.env.HORIZON_URL || 'https://horizon-testnet.stellar.org';
const FRIENDBOT_URL = process.env.FRIENDBOT_URL || 'https://friendbot.stellar.org';
const ISSUER_SECRET = process.env.ISSUER_SECRET || '';
const NETWORK_PASSPHRASE = Networks.TESTNET;
const USDC_ISSUER = Keypair.fromSecret(ISSUER_SECRET).publicKey();
const USDC_ASSET = new Asset('USDC', USDC_ISSUER);

if (!ISSUER_SECRET) {
  throw new Error('ISSUER_SECRET is required (generated by scripts/testnet-journey.sh)');
}

// ── Evidence ──────────────────────────────────

const evidence: Record<string, any> = {
  runAt: new Date().toISOString(),
  network: 'testnet',
  gatewayUrl: GATEWAY_URL,
  horizonUrl: HORIZON_URL,
  usdcIssuer: USDC_ISSUER,
  steps: {},
};

function step(name: string, data: Record<string, any>) {
  evidence.steps[name] = data;
  console.log(`  ✓ ${name}`);
}

let stepFailures = 0;
function check(name: string, condition: boolean, detail?: string) {
  if (condition) {
    console.log(`    ✅ ${name}`);
  } else {
    stepFailures++;
    console.error(`    ❌ ${name}${detail ? ` — ${detail}` : ''}`);
  }
}

// ── Horizon helpers ───────────────────────────

const server = new Horizon.Server(HORIZON_URL);

async function friendbotFund(address: string, label: string): Promise<void> {
  const res = await fetch(`${FRIENDBOT_URL}/?addr=${address}`, { method: 'GET' });
  if (!res.ok) {
    // Already-funded accounts return 400 — acceptable only if the account
    // actually exists with a balance.
    const account = await server.loadAccount(address);
    if (account.balances.length === 0) {
      throw new Error(`friendbot failed for ${label} (${address}): ${res.status}`);
    }
    console.log(`    (${label} already funded — reused)`);
    return;
  }
  const body: any = await res.json();
  console.log(`    (${label} funded: ${body.hash})`);
  // Wait for the funding ledger to be visible before building on the account.
  await server.transactions().transaction(body.hash).call();
}

async function submitTx(tx: any, label: string): Promise<any> {
  try {
    const result = await server.submitTransaction(tx, { skipMemoRequiredCheck: true });
    return result;
  } catch (err: any) {
    // Surface Horizon's result codes so failures are diagnosable from the
    // evidence output, not just the raw AxiosError.
    const detail =
      err?.response?.data?.extras?.result_codes || err?.response?.data?.detail || err?.message;
    throw new Error(`${label} submission failed: ${JSON.stringify(detail)}`);
  }
}

async function submitSigned(secret: string, txXdr: string, label: string): Promise<any> {
  // txs from buildSigned are already signed; re-signing would add a duplicate
  // signature and Horizon rejects it (tx_bad_auth_extra).
  const tx = TransactionBuilder.fromXDR(txXdr, NETWORK_PASSPHRASE);
  return submitTx(tx, label);
}

async function buildSigned(
  secret: string,
  label: string,
  ops: any[],
  memo?: string,
): Promise<{ txXdr: string; txHash: string }> {
  const keypair = Keypair.fromSecret(secret);
  const account = await server.loadAccount(keypair.publicKey());
  const builder = new TransactionBuilder(account, {
    fee: BASE_FEE,
    networkPassphrase: NETWORK_PASSPHRASE,
  });
  for (const op of ops) builder.addOperation(op);
  if (memo) builder.addMemo(new Memo(MemoText, memo));
  builder.setTimeout(300);
  const built = builder.build();
  built.sign(keypair);
  return { txXdr: built.toXDR(), txHash: built.hash().toString('hex') };
}

const balances = async (address: string): Promise<Array<{ asset: string; balance: string }>> =>
  (await server.loadAccount(address)).balances.map((b: any) => ({
    asset:
      b.asset_type === 'native' ? 'XLM' : `${b.asset_code}:${(b.asset_issuer || '').slice(0, 8)}`,
    balance: b.balance,
  }));

// ── Main ──────────────────────────────────────

async function main() {
  const issuer = Keypair.fromSecret(ISSUER_SECRET);
  const payer = Keypair.random();
  const receiver = Keypair.random();
  console.log('\n═══ x402 Live Stellar Testnet Journey ═══');
  console.log(`  issuer   ${issuer.publicKey()}`);
  console.log(`  payer    ${payer.publicKey()}`);
  console.log(`  receiver ${receiver.publicKey()}`);

  // 1. Fund accounts.
  console.log('\n── Step 1: fund fresh accounts (friendbot) ──');
  await friendbotFund(issuer.publicKey(), 'issuer');
  await friendbotFund(payer.publicKey(), 'payer');
  await friendbotFund(receiver.publicKey(), 'receiver');
  step('fund', {
    issuer: issuer.publicKey(),
    payer: payer.publicKey(),
    receiver: receiver.publicKey(),
  });

  // 2. Trustlines + mint. The payer needs one to hold USDC; the receiver
  // needs one because the gateway pays the provider wallet directly (a
  // non-native payment to an account without a trustline fails op_no_trust).
  console.log('\n── Step 2: payer + receiver trustlines, issuer mints 100 USDC ──');
  const payerTrustline = await buildSigned(payer.secret(), 'payer-trustline', [
    Operation.changeTrust({ asset: USDC_ASSET }),
  ]);
  await submitSigned(payer.secret(), payerTrustline.txXdr, 'payer-trustline');
  console.log(`    payer trustline tx: ${payerTrustline.txHash}`);
  const receiverTrustline = await buildSigned(receiver.secret(), 'receiver-trustline', [
    Operation.changeTrust({ asset: USDC_ASSET }),
  ]);
  await submitSigned(receiver.secret(), receiverTrustline.txXdr, 'receiver-trustline');
  console.log(`    receiver trustline tx: ${receiverTrustline.txHash}`);
  step('trustline', {
    payerTxHash: payerTrustline.txHash,
    receiverTxHash: receiverTrustline.txHash,
    asset: 'USDC:' + USDC_ISSUER,
  });

  const mint = await buildSigned(issuer.secret(), 'mint', [
    Operation.payment({ destination: payer.publicKey(), asset: USDC_ASSET, amount: '100' }),
  ]);
  await submitSigned(issuer.secret(), mint.txXdr, 'mint');
  console.log(`    mint tx: ${mint.txHash}`);
  step('mint', { txHash: mint.txHash, amount: '100 USDC' });

  // 3. Seed provider + route for the gateway (idempotent upsert).
  console.log('\n── Step 3: seed provider + route ──');
  const provider = await prisma.provider.upsert({
    where: { id: 'journey-provider' },
    // Re-point the payout wallet at the current receiver every run — a stale
    // address from a previous run would receive the payment instead.
    update: {
      walletAddress: receiver.publicKey(),
      payoutWalletAddress: receiver.publicKey(),
    },
    create: {
      id: 'journey-provider',
      name: 'Testnet Journey Provider',
      walletAddress: receiver.publicKey(),
      payoutWalletAddress: receiver.publicKey(),
      active: true,
    },
  });
  const route = await prisma.route.upsert({
    where: {
      providerId_path_model: {
        providerId: provider.id,
        path: '/v1/chat/completions',
        model: 'gpt-4-journey',
      },
    },
    update: {},
    create: {
      providerId: provider.id,
      path: '/v1/chat/completions',
      upstreamUrl: 'https://httpbin.org/post',
      model: 'gpt-4-journey',
      pricingModel: 'flat',
      flatPrice: '1000000',
      acceptedAssets: ['USDC'],
      rateLimit: 100,
      active: true,
    },
  });
  step('seed', { providerId: provider.id, routeId: route.id });

  // 4. Unpaid request → 402 quote.
  console.log('\n── Step 4: unpaid request → HTTP 402 + quote ──');
  const unpaid = await fetch(`${GATEWAY_URL}/api/v1/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'gpt-4-journey',
      messages: [{ role: 'user', content: 'Hello from the live testnet journey!' }],
    }),
  });
  const unpaidBody: any = await unpaid.json();
  check('HTTP 402', unpaid.status === 402, `got ${unpaid.status}`);
  check('quote present', !!unpaidBody.quote, 'no quote in body');
  const quote = unpaidBody.quote;
  check('quote.amount == 1000000 stroops', quote?.amount === '1000000', quote?.amount);
  check('quote asset is USDC', quote?.asset === 'USDC', quote?.asset);
  check(
    'quote assetIssuer is the journey issuer',
    quote?.assetIssuer === USDC_ISSUER,
    quote?.assetIssuer,
  );
  step('quote', { quote });

  // 5. Pay the quoted amount with the repo wallet builder.
  console.log('\n── Step 5: pay the quote on-chain ──');
  const amountUnits = stroopsToUnits(quote.amount); // stroops → 0.1 USDC
  const payment = await buildPaymentTransaction({
    sourceSecret: payer.secret(),
    destination: quote.paymentAddress,
    amount: amountUnits,
    asset: 'USDC',
    assetIssuer: USDC_ISSUER,
    memo: quote.memo,
    network: 'testnet',
    horizonUrl: HORIZON_URL,
  });
  // v12 SDK requires a Transaction object (not an XDR string).
  const paymentTx = TransactionBuilder.fromXDR(payment.txXdr, NETWORK_PASSPHRASE);
  const submitted = await submitTx(paymentTx, 'payment');
  console.log(`    payment tx hash: ${payment.txHash}`);
  console.log(`    ledger: ${submitted.ledger}`);
  step('pay', {
    txHash: payment.txHash,
    ledger: submitted.ledger,
    amount: `${amountUnits} USDC`,
    to: quote.paymentAddress,
    memo: quote.memo,
    horizon: `${HORIZON_URL}/transactions/${payment.txHash}`,
  });

  // 6. Retry with the payment hash → 200 + receipt.
  console.log('\n── Step 6: retry with X-Payment-Hash → HTTP 200 ──');
  const paid = await fetch(`${GATEWAY_URL}/api/v1/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Payment-Hash': payment.txHash },
    body: JSON.stringify({
      model: 'gpt-4-journey',
      messages: [{ role: 'user', content: 'Hello from the live testnet journey!' }],
    }),
  });
  const paidBody: any = await paid.json();
  check('HTTP 200', paid.status === 200, `got ${paid.status}`);
  const receipt = paid.headers.get('x-payment-receipt');
  check('X-Payment-Receipt header present', !!receipt);
  let receiptJson: any = null;
  if (receipt) {
    receiptJson = JSON.parse(receipt);
    check(
      'receipt.txHash matches the payment',
      receiptJson.txHash === payment.txHash,
      receiptJson.txHash,
    );
    check('receipt.status == confirmed', receiptJson.status === 'confirmed', receiptJson.status);
  }
  step('forward', { status: paid.status, receipt: receiptJson, bodyId: paidBody?.id });

  // 7. Replay the same hash → 402 single-use.
  console.log('\n── Step 7: replay the same hash → HTTP 402 (single-use) ──');
  const replay = await fetch(`${GATEWAY_URL}/api/v1/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Payment-Hash': payment.txHash },
    body: JSON.stringify({
      model: 'gpt-4-journey',
      messages: [{ role: 'user', content: 'replay' }],
    }),
  });
  const replayBody: any = await replay.json();
  check('HTTP 402', replay.status === 402, `got ${replay.status}`);
  check(
    'rejected as already used',
    /already been used/i.test(replayBody?.message || ''),
    replayBody?.message,
  );
  step('replay-rejected', { status: replay.status, message: replayBody?.message });

  // 8. A hash that never existed → 402 fail-closed.
  console.log('\n── Step 8: forged/unknown hash → HTTP 402 (fail-closed) ──');
  const forged = await fetch(`${GATEWAY_URL}/api/v1/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Payment-Hash': 'f'.repeat(64) },
    body: JSON.stringify({
      model: 'gpt-4-journey',
      messages: [{ role: 'user', content: 'forged' }],
    }),
  });
  const forgedBody: any = await forged.json();
  check('HTTP 402', forged.status === 402, `got ${forged.status}`);
  check(
    'verification failed reason surfaced',
    /verification failed|not found/i.test(forgedBody?.message || ''),
    forgedBody?.message,
  );
  step('forged-rejected', { status: forged.status, message: forgedBody?.message });

  // 9. Final balances — the money visibly moved.
  console.log('\n── Step 9: final balances ──');
  const payerB = await balances(payer.publicKey());
  const receiverB = await balances(receiver.publicKey());
  const issuerB = await balances(issuer.publicKey());
  step('balances', { payer: payerB, receiver: receiverB, issuer: issuerB });
  const receiverUsdc = receiverB.find((b) => b.asset.startsWith('USDC'));
  check(
    'receiver holds the paid USDC (0.1)',
    receiverUsdc && Number(receiverUsdc.balance) >= 0.099,
    receiverUsdc?.balance,
  );

  // Evidence output (run from repo root so relative paths are stable).
  const outPath = process.env.EVIDENCE_PATH || 'docs/evidence/testnet-journey.json';
  const fs = await import('fs');
  fs.mkdirSync('docs/evidence', { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(evidence, null, 2));
  console.log(`\n📄 Evidence written to ${outPath}`);

  console.log(
    `\n═══ ${stepFailures === 0 ? 'ALL CHECKS PASSED ✅' : `${stepFailures} CHECKS FAILED ❌`} ═══`,
  );
  if (stepFailures > 0) process.exit(1);
}

main().catch((err) => {
  console.error('\nJourney failed:', err);
  process.exit(1);
});
